version: '3'
services:
        lime_node:
                image: lime
                volumes:
                        - "./videos:/home/lime/videos"
                        - "/tmp/.X11-unix:/tmp/.X11-unix"
                        - "./log:/home/lime/log"
                devices: 
                        - "/dev/video1:/dev/video0"
                env_file:
                        - ".env"
                cap_add:
                        - ALL
